Feature/header
Incubateur-Web/dreamtastic-website pull request #4
Opened 2020-10-14 15:53 UTC by JeremyGendre

2020-10-14 20:22 UTC, MartinPELCAT requested changes

2020-10-14 20:22 UTC, MartinPELCAT commented on src/components/Header/HeaderLink.tsx
> +  onClick?(): any;
C'est :void je crois

2020-10-14 20:22 UTC, MartinPELCAT commented on src/components/Header/HeaderLink.tsx
> +export default function HeaderLink(props: Props) {
decomposition ? {path, onClick, active, path}: Props

2020-10-14 20:22 UTC, MartinPELCAT commented on src/components/Header/HeaderProfileSubmenu.tsx
> +export default function HeaderProfileSubmenu(props: Props) {
{...}: Props ?

2020-10-14 20:22 UTC, MartinPELCAT commented on src/components/Loader.tsx
> +export default function Loader(props: { size?: number }) {
{size}: {size?:number } si tu fais pas de type

2020-10-14 20:22 UTC, MartinPELCAT commented on src/layouts/DefaultLayout.tsx
> +import Header from "../components/Header/Header";
nom du dossier en minuscule ?

2020-10-15 07:05 UTC, MartinPELCAT approved these changes

2020-10-15 13:41 UTC, Lelberto approved these changes

2020-10-15 13:51 UTC, merged